image: gitpod/workspace-full-vnc

tasks:
- name: SETUP - GITHUB
  init: |
    git clone https://github.com/LiaOb21/colora.git colora-pipeline
    cd colora

- name: SETUP - DOWNLOAD OatkTB
  init: |
    git clone https://github.com/c-zhou/OatkDB.git
    mv OatkDB/test_data ./oatk_data

- name: SETUP - DOWNLOAD BUSCO
  init: |
    mkdir busco_db
    cd busco_db
    wget https://busco-data.ezlab.org/v5/data/lineages/saccharomycetes_odb10.2024-01-08.tar.gz
    tar -xzf saccharomycetes_odb10.2024-01-08.tar.gz
    cd ..

- name: SETUP - MAMBA ENVIRONMENT
  command: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n ncbi_fcsgx bioconda::ncbi-fcs-gx -y
    mamba create -n snakemake -c conda-forge -c bioconda snakemake -y

    mamba activate ncbi_fcsgx
    mkdir gx_test_db
    cd gx_test_db
    sync_files.py get --mft https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/test-only/test-only.manifest --dir ./test-only
    mamba deactivate
    gp sync-done bundle

- name: MAIN - TERMINAL TO USE
  init: gp sync-await bundle
  command: |
    cd /workspace
    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate snakemake
    export PATH=/workspace:$PATH
    gp preview https://www.thebgacademy.org/BGA24/sessions/colora-24
    clear
    echo 'Welcome to the Colora Session'

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
