image: gitpod/workspace-full-vnc

- name: SETUP - MAMBA ENVIRONMENT
  init: |
    echo "Hello there - Welcome to GitPod

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
